spring:
  application:
    name: Blognest
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5444/bsdb
    username: bsdb
    password: password
  mvc:
    favicon:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

app:
  jwt:
    # Signing key for HS512 algorithm http://www.allkeysgenerator.com/
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 60
  cors:
    allowed-origins: http://localhost:5173, http://localhost:5174

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG